# Generated by Django 6.0.3 on 2026-04-03 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукти'},
        ),
        migrations.AlterModelOptions(
            name='sklad',
            options={'verbose_name': 'Склади'},
        ),
    ]
