# Generated by Django 6.0.3 on 2026-04-03 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_product_sklad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sklad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.sklad'),
        ),
    ]
