# Generated by Django 6.0.3 on 2026-04-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
