# Generated by Django 6.0.3 on 2026-04-04 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orders_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='proudct',
            new_name='product',
        ),
    ]
