# Generated by Django 6.0.3 on 2026-04-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_proudct_orders_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
