# Generated by Django 6.0.3 on 2026-04-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_product_price_alter_orders_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='count_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
